### ISSUE TITLE
Resource leak in FtpClientTemplate.downloadFile

### ISSUE THREAD

**Issue by ZhaoChunlei** [jayknoxqu/ftp-pool#3]
ftpClient = **ftpClientPool.borrowObject();**
if (!FTPReply.isPositiveCompletion(ftpClient.getReplyCode())) {
   return false;
}
ftpClient = **ftpClientPool.borrowObject();**

**Comment by jayknoxqu** [comment]
You update the code and retry

**Comment by ZhaoChunlei** [comment]
cool.
